Repository Hirlam/PlayGround, pull requests merged in 2021-12, with the labels that each got.

#54 Revert "Update to test file"
  IcandoPRs/alan-hally
Labels: bug

#60 Create alanhally.md
  IcandoPRs/alan-hally
  IcandoPRs/alan-hally-2
  docs/src/alanhally.md
Labels: documentation

#22 Create marieminvielle
  IcandoPRs/marieminvielle
Labels: enhancement

#47 Create test_mda
  IcandoPRs/test_mda
  IcandoPRs/test_mda2
Labels: enhancement
